
server:
  port: 8080
  application:
    name: project-z

spring:
  config:
    import: nacos:project-z.json
  cloud:
    nacos:
      config:
        namespace: public
        enabled: true
        server-addr: 127.0.0.1:8848
        file-extension: json
        group: DEFAULT_GROUP

datasource-mod:
  nacos-enable: true
  nacos-dataId: datasource-set
  nacos-group: DEFAULT_GROUP
  nacos-server-addr: 127.0.0.1:8848

# ... existing code ...
