### HttpClinet 用例
POST http://localhost:8080/client/post
Content-Type: application/json

{
  "headers": {
    "path": "get",
    "method": "get"
  },
  "requestType": "get",
  "url": "http://localhost:8089//analyse/get"
}

### ClientDemo Analyse Get
GET http://localhost:8888/client/analyseGet


### ClientDemo Analyse Post
POST http://localhost:8888/client/analysePost

### Analyse Get
GET http://localhost:8089/analyse/get?name=get

### Analyse Post
POST http://localhost:8089/analyse/post
Content-Type: application/json

{
  "name": "post"
}


### clinet analysePostJson
GET http://127.0.0.1:8888/client/analysePostJson?id=1

### database set
POST http://localhost:8888/client/post
Content-Type: application/json

{
  "url": "http://localhost:9091/datasource/getDataSourceSets",
  "requestType": "get",
  "body": ""
}
