
server:
  port: 8000

spring:
  application:
    name: DataSourceModTest
  profiles:
    active: private

#datasource-set:
#  url: "jdbc:sqlserver://192.168.8.13:1433;databaseName=test"

datasource-mod:
#  nacos-enable: false
  file-path: "/datasource/datasourceset.json"
  mapper-locations:
    d1: classpath:mapper/test1/*.xml
    d2: classpath:mapper/test2/*.xml
  mapper-base-package:
    d1: com.example.demo.mapper
    d2: com.example.demo.mapper
  logic:
    # names 用来记录所有的数据源名称
    names: d1, d2
#    # maps 用来记录数据源名称和数据源别名
#    maps:
#      remote: R
#      local: L
    # 默认账套
    default: remote
  mybatis-config:
    cache-enabled: false
    map-underscore-to-camel-case: false
    call-setters-on-nulls: true
    return-instance-for-empty-row: false
  config:
    ip: "[ip]"
    port: "[port]"
    dbName: "[dbName]"
    mssql:
      driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
      jdbcUrl: "jdbc:sqlserver://[ip]:[port];databaseName=[dbName]"
    mysql:
      driverClassName: "com.mysql.jdbc.Driver"
      jdbcUrl: "jdbc:mysql://[ip]:[port]/[dbName]?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC"

logging:
  level:
    org.aileen: debug