staticserver:
  port: 8888


#最大连接数
http:
  maxTotal: 100
  #设置到某个路由的最大连接数
  defaultMaxPerRoute: 20
  #连接超时时间（单位毫秒）
  connectTimeout: 10000
  #从连接池中获取到连接的最长时间（单位毫秒）
  connectionRequestTimeout: 5000
  #数据传输的最长时间（单位毫秒）
  socketTimeout: 10000
  #空闲永久连接检查间隔，官方推荐使用这个来检查永久链接的可用性，而不推荐每次请求的时候才去检查
  validateAfterInactivity: 2000
logging:
  level:
    org.tutor: debug
